/// Lightweight bilingual (AR/EN) string table with RTL support.
library;

class S {
  final bool ar;
  const S(this.ar);

  String t(String en, String arText) => ar ? arText : en;

  // General
  String get appTitle => t('Smart Institute', 'المعهد الذكي');
  String get dashboard => t('Dashboard', 'لوحة التحكم');
  String get newRegistration => t('New Registration', 'تسجيل جديد');
  String get students => t('Students', 'الطلاب');
  String get groups => t('Groups & Schedule', 'المجموعات والجدول');
  String get receipts => t('Receipts', 'الإيصالات');
  String get settings => t('Settings', 'الإعدادات');
  String get language => t('Language', 'اللغة');
  String get currency => t('Currency', 'العملة');
  String get save => t('Save', 'حفظ');
  String get cancel => t('Cancel', 'إلغاء');
  String get next => t('Next', 'التالي');
  String get back => t('Back', 'رجوع');
  String get search => t('Search', 'بحث');
  String get name => t('Name', 'الاسم');
  String get phone => t('Phone', 'الهاتف');
  String get guardianName => t('Guardian name', 'اسم ولي الأمر');
  String get guardianPhone => t('Guardian phone', 'هاتف ولي الأمر');
  String get required => t('Required', 'حقل مطلوب');

  // Wizard steps
  String get stepStudent => t('Student', 'الطالب');
  String get stepSubject => t('Subject', 'المادة');
  String get stepGroup => t('Group & Teacher', 'المجموعة والمدرس');
  String get stepPayment => t('Payment & Receipt', 'الدفع والإيصال');

  String get scanBarcodeHint =>
      t('Scan barcode or search by name / phone…', 'امسح الباركود أو ابحث بالاسم / الهاتف…');
  String get scanBarcodeHelp => t(
      'Barcode scanners type the code and press Enter automatically.',
      'قارئ الباركود يكتب الرمز ويضغط Enter تلقائياً.');
  String get studentNotFound => t('No student found', 'لا يوجد طالب مطابق');
  String get addNewStudent => t('Add new student', 'إضافة طالب جديد');
  String get selectedStudent => t('Selected student', 'الطالب المحدد');
  String get barcode => t('Barcode', 'الباركود');
  String get autoGenerated => t('auto-generated', 'يُنشأ تلقائياً');
  String get enrolledSince => t('Enrolled since', 'مسجل منذ');

  String get chooseSubject => t('Choose a subject', 'اختر المادة');
  String get basePrice => t('Base price', 'السعر الأساسي');
  String get months => t('months', 'أشهر');
  String get alreadyEnrolled => t('Already enrolled', 'مسجل مسبقاً');

  String get chooseGroup => t('Choose group & teacher', 'اختر المجموعة والمدرس');
  String get seatsLeft => t('seats left', 'مقاعد متبقية');
  String get full => t('FULL', 'مكتملة');
  String get conflict => t('Schedule conflict!', 'تعارض في المواعيد!');
  String get conflictWith => t('Conflicts with', 'يتعارض مع');
  String get vip => t('VIP', 'مميزة');

  String get invoiceSummary => t('Invoice summary', 'ملخص الفاتورة');
  String get price => t('Price', 'السعر');
  String get discount => t('Discount', 'الخصم');
  String get netTotal => t('Net total', 'الصافي');
  String get amountPaid => t('Amount paid', 'المبلغ المدفوع');
  String get remaining => t('Remaining', 'المتبقي');
  String get completeAndPrint =>
      t('Complete registration & print receipt', 'إتمام التسجيل وطباعة الإيصال');
  String get receipt => t('Receipt', 'إيصال');
  String get receiptNo => t('Receipt No.', 'رقم الإيصال');
  String get date => t('Date', 'التاريخ');
  String get student => t('Student', 'الطالب');
  String get subject => t('Subject', 'المادة');
  String get teacher => t('Teacher', 'المدرس');
  String get group => t('Group', 'المجموعة');
  String get schedule => t('Schedule', 'الموعد');
  String get thankYou => t('Thank you!', 'شكراً لكم!');
  String get print => t('Print', 'طباعة');
  String get done => t('Done', 'تم');
  String get registrationSuccess =>
      t('Registration completed successfully', 'تم التسجيل بنجاح');
  String get startNew => t('New registration', 'تسجيل جديد');

  // Dashboard
  String get todayRevenue => t("Today's revenue", 'إيرادات اليوم');
  String get totalStudents => t('Total students', 'إجمالي الطلاب');
  String get activeGroups => t('Active groups', 'المجموعات النشطة');
  String get totalRegistrations => t('Registrations', 'التسجيلات');
  String get topSubjects => t('Most requested subjects', 'أكثر المواد طلباً');
  String get topTeachers => t('Top teachers by enrollment', 'المدرسون الأكثر تسجيلاً');
  String get recentActivity => t('Recent registrations', 'آخر التسجيلات');
  String get occupancy => t('Occupancy', 'الإشغال');

  // Administration / pricing
  String get administration => t('Administration', 'الإدارة');
  String get pricing => t('Pricing', 'الأسعار');
  String get subjectsPricing => t('Course prices', 'أسعار الكورسات');
  String get teachersPricing => t('Teacher session prices', 'أسعار جلسات المدرسين');
  String get groupsPricing => t('Group price overrides', 'أسعار خاصة للمجموعات');
  String get sessionPrice => t('Session price', 'سعر الجلسة');
  String get coursePrice => t('Full course price', 'سعر الكورس الكامل');
  String get totalHours => t('Total hours', 'عدد الساعات');
  String get hours => t('hours', 'ساعة');
  String get durationMonthsLabel => t('Duration (months)', 'المدة (أشهر)');
  String get priceOverrideLabel =>
      t('Special price (empty = subject price)', 'سعر خاص (فارغ = سعر المادة)');
  String get edit => t('Edit', 'تعديل');
  String get updated => t('Updated successfully', 'تم التحديث بنجاح');
  String get useSubjectPrice => t('Uses subject price', 'يعتمد سعر المادة');

  // Discounts
  String get discounts => t('Discounts', 'الخصومات');
  String get addDiscount => t('Add discount', 'إضافة خصم');
  String get discountScope => t('Applies to', 'يُطبق على');
  String get scopeStudent => t('Student', 'طالب');
  String get scopeGroup => t('Group', 'مجموعة');
  String get scopeSubject => t('Subject', 'مادة');
  String get scopeTeacher => t('Teacher', 'مدرس');
  String get discountTypeLabel => t('Type', 'النوع');
  String get percent => t('Percent %', 'نسبة %');
  String get fixedAmount => t('Fixed amount', 'مبلغ ثابت');
  String get valueLabel => t('Value', 'القيمة');
  String get noteLabel => t('Note', 'ملاحظة');
  String get target => t('Target', 'الهدف');
  String get activeLabel => t('Active', 'مفعّل');
  String get inactiveLabel => t('Inactive', 'موقوف');
  String get delete => t('Delete', 'حذف');
  String get noDiscounts => t('No discount rules yet', 'لا توجد قواعد خصم بعد');
  String get autoDiscountApplied =>
      t('Automatic discount applied', 'تم تطبيق خصم تلقائي');
  String get confirmDelete =>
      t('Delete this discount rule?', 'هل تريد حذف قاعدة الخصم؟');

  // Days (ISO: 1 = Monday)
  List<String> get days => ar
      ? const ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد']
      : const ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  String day(int isoDay) => days[isoDay - 1];

  String time(int hour, int minute) {
    final h12 = hour % 12 == 0 ? 12 : hour % 12;
    final mm = minute.toString().padLeft(2, '0');
    final pm = hour >= 12;
    final suffix = ar ? (pm ? 'م' : 'ص') : (pm ? 'PM' : 'AM');
    return '$h12:$mm $suffix';
  }
}
